# The arithmetic mean computed from grouped data

## Problem 3-19
Use the method of Problem [3.18(a)](03%20Properties%20of%20the%20arithmetic%20mean.ipynb#Problem-3-18-a) to find the arithmetic mean of the numbers $5, 8, 11, 9, 12, 6, 14,$ and $10$, choosing as the "guessed mean" $A$ the values (a) $9$ and (b) $20$.

### Solution 3-19
(a) The deviations of the given numbers from $9$ are $-4, -1, 2, 0, 3, -3, 5,$ and $1$, and the sum of the deviations is $\sum{d}=-4-1+2+0+3-3+5+1=3$. Thus

\begin{align}
\bar{X}=A+\frac{\sum{d}}{N}=9+\frac{3}{8}=9.375
\end{align}

(b) The deviations of the given numbers from $20$ are $-15, -12, -9, -11, -8, -14, -6,$ and $-10,$ and $\sum{d-85}$. Thus

\begin{align}
\bar{X}=A+\frac{\sum{d}}{N}=20+\frac{(-85)}{8}=9.375
\end{align}

---

## Problem 3-20
Use the method of Problem [3.18(b)](03%20Properties%20of%20the%20arithmetic%20mean.ipynb#Problem-3-18-b) to find the aritmetic mean of the heights of the $100$ male students at XYZ University (see Problem [3.15](02%20The%20arithmetic%20mean.ipynb#Problem-3-15)).

### Solution 3-20
The work may be arrainged as in Table [3.2](#Table-3-2). We take the guessed mean $A$ to be the class mark $67$ (which has the largest frequency), although any class mark can be used for $A$. Note that the computations are simpler than those in Problem [3.15](02%20The%20arithmetic%20mean.ipynb#Problem-3-15). To shorten the labor even more, we can proceed as in Problem [3.22](#Problem-3-22), where use is made of the fact that the deviations (column 2 of Table [3.2](#Table-3-2)) are all integer multiples of the class-interval size.

In [1]:
load('../../Saves//Table_3.1.Rdata')
p3.20.X <- Table.3.1[,1]
p3.20.A <- Table.3.1[ceiling(nrow(Table.3.1)/2),1]
p3.20.d <- Table.3.1[,1]-p3.20.A
p3.20.f <- Table.3.1[,2]
p3.20.fd <- p3.20.f*p3.20.d
Table.3.2 <- matrix(c(p3.20.X, p3.20.d, p3.20.f, p3.20.fd), nrow=nrow(Table.3.1))
rownames(Table.3.2) <- rownames(Table.3.1)
colnames(Table.3.2) <- c('Class Mark (X)', 'Deviation d = X - A', 'Frequency (f)', 'fd')

<a id='Table-3-2'></a>

In [2]:
Table.3.2

      Class Mark (X) Deviation d = X - A Frequency (f) fd
60-62 61             -6                   5            -30
63-65 64             -3                  18            -54
66-68 67              0                  42              0
69-71 70              3                  27             81
72-74 73              6                   8             48

\begin{align}
\bar{X}=A+\frac{\sum{fd}}{N}=67+\frac{45}{100}=67.45\text{ in}
\end{align}

In [3]:
p3.20.N <- sum(Table.3.2[,3])
p3.20.fd.sum <- sum(p3.20.fd)
(p3.20.X.bar <- p3.20.A+p3.20.fd.sum/p3.20.N)

[1] 67.45

---

## Problem 3-21
Let $d_j=X_j-A$ denote the deviations of any class mark $X_j$ in a frequency distribution from a given class mark $A$. Show that if all class intervals have equal size $c$, then (a) the deviations are all multiples of $c$ (i.e., $d_j=cu_j$, where $u_j=0,\pm1, \pm2,\ldots$) and (b) the arithmetic mean can be computed from the formula

\begin{align}
\bar{X}=A+\left(\frac{\sum{fu}}{N}\right)c
\end{align}

### Solution 3-21
<a id='Solution-3-21-a'></a>
(a)  
The result is illustrated in Table [3.2](#Table-3-2) of Problem [3.20](#Problem-3-20), where it is observed that the deviations in c0lumn 2 are all multiples of the class-interval size $c=3$ in.

To see that the result is true in general, note that if $X_1, X_2, X_3,\ldots$ are successive class markes, their common difference will for this case be equal to $c$, so that $X_2=X_1+c$, $X_3=X_1+2c$, and in general $X_j=X_1+(j-1)c$. Then any two class markes $X_p$ and $X_q$, for example, will differ by

\begin{align}
X_p-X_q=[X_1+(p-1)c]-[X_1+(q-1)c]=(p-q)c
\end{align}

which is a multiple of $c$.

<a id='Solution-3-21-b'></a>
(b)  
By part (a), the deviations of all the class marks from any given one are multiples of $c$ (i.e., $d_j=cu_j$). Then, using Problem [3.18(b)](03%20Properties%20of%20the%20arithmetic%20mean.ipynb#Problem-3-18-b), we have

\begin{align}
\bar{X}=A\frac{\sum{f_jd_j}}{N}=A+\frac{\sum{f_j(cu_j)}}{N}=A+c\frac{\sum{f_ju_j}}{N}=A+\left(\frac{\sum{fu}}{N}\right)c
\end{align}

Note that this is equivalent to the result $\bar{X}=A+c\bar{u}$, which can be obtained from $\bar{X}=A+\bar{d}$ by placing $d=cu$ and observing that $\bar{d}=c\bar{u}$ (see Problem [3.18](03%20Properties%20of%20the%20arithmetic%20mean.ipynb#Problem-3-18).

---

## Problem 3-22
Use the result of Problem [3.21(b)](#Solution-3-21-b) to find the mean height of the $100$ male students at XYZ University (see Problem [3.20](#Problem-3-20)).

### Solution 3-22
The work may be arranged as in Table [3.3](#Table-3-3). The method is called the _coding method_ and should be employed whenever possible.

In [24]:
load('../../Saves/Table_2.1.Rdata')
p3.22.X <- c(61, 64, 67, 70, 73)
p3.22.length <- length(Table.2.1$Freq)
p3.22.A.idx <- ceiling(p3.22.length/2)
p3.22.A <- p3.22.X[p3.22.A.idx]
p3.22.u <- seq(1, p3.22.length, by=1)-p3.22.A.idx
p3.22.f <- Table.2.1$Freq
p3.22.fu <- p3.22.f*p3.22.u
Table.3.3 <- data.frame(X=p3.22.X, u=p3.22.u, f=p3.22.f, fu=p3.22.fu)
#Table.3.3 <- matrix(c(p3.22.X, p3.22.u, p3.22.f, p3.22.fu), nrow=nrow(Table.2.1))
#colnames(Table.3.3) <- c("X", "u", "f", "fu")

<a id='Table-3-3'></a>

In [20]:
Table.3.3

  X  u  f  fu
1 61 -2  5 -10
2 64 -1 18 -18
3 67  0 42   0
4 70  1 27  27
5 73  2  8  16

\begin{align}
\bar{X}=A+\left(\frac{\sum{fu}}{N}\right)c=67+\left(\frac{15}{100}\right)(3)=67.45\text{ in}
\end{align}

---

## Problem 3-23
Compute the mean weekly wage of the $65$ employees at the P&R Company from the frequency distribution in Table [2.6](../../02%20Chapter%202%20Frequency%20Distributions/02%20Solved%20Problems/02%20Frequency%20Distributions,%20Histograms,%20and%20Frequency%20Polygons.ipynb#Table-2-6), using (a) the long method and (b) the coding method.

### Solution 3-23
Tables [3.4](#Table-3-4) and [3.5](#Table-3-5) show the solutions to (a) and (b), respectively.

In [ ]:
load('../../Saves/Table_2.6.Rdata')
p3.23.nrow <- nrow(Table.2.6)
p3.23.X <- c(255.00, 265.00, 275.00, 285.00, 295.00, 305.00, 315.00)
p3.23.f <- Table.2.6[,1]
p3.23.N <- sum(p3.23.f)
p3.23.fX <- p3.23.X*p3.23.f
p3.23.sum.fx <- sum(p3.23.fX)
Table.3.4 <- matrix(c(p3.23.X, p3.23.f, p3.23.fX), nrow=p3.23.nrow)
colnames(Table.3.4) <- c('X', 'f', 'fX')

#### Table 3-4

In [ ]:
Table.3.4

In [ ]:
p3.23.A.idx <- 3
p3.23.A <- p3.23.X[p3.23.A.idx]
p3.23.u <- seq(1, p3.23.nrow, by=1)-p3.23.A.idx
p3.23.fu <- p3.23.f*p3.23.u
Table.3.5 <- matrix(c(p3.23.X, p3.23.u, p3.23.f, p3.23.fu), nrow=p3.23.nrow)
colnames(Table.3.5) <- c('X', 'u', 'f', 'fu')

#### Table 3-5

In [ ]:
Table.3.5

If might be supposed that error would be introduced into these tables since the class marks are actually $\$254.995$, $\$264.995$, etc., instead of $\$255.00$, $\$265.00$, etc. If in Table [3.4](#Table-3-4) these true class marks are used instead, then $\bar{X}$ turns out to be $\$279.77$, and the difference is negligible.

\begin{align}
\bar{X}=\frac{\sum{fX}}{N}=\frac{\$18.185.00}{65}=\$279.77 \ \ \ \ \ \bar{X}=A+\left(\frac{\sum{fu}}{N}\right)c=\$275.00+\frac{31}{65}(\$10.00)=\$279.77
\end{align}

---

## Problem 3-24
Using Table [2.10(d)](../../02%20Chapter%202%20Frequency%20Distributions/02%20Solved%20Problems/02%20Frequency%20Distributions,%20Histograms,%20and%20Frequency%20Polygons.ipynb#Table-2-10-d) find the mean wage of the $70$ employees at the P&R Company.

### Solution 3-24
In this case the class intervals do not have equal size and we must use the long method, as shown in Table [3.6](#Table-3-6).

In [ ]:
load('../../Saves/Table_2.10d.Rdata')
p3.24.nrow <- nrow(Table.2.10.d)
p3.24.X <- c(255.00, 265.00, 275.00, 285.00, 295.00, 310.00, 350.00)
p3.24.f <- Table.2.10.d[,1]
p3.24.fX <- p3.24.f*p3.24.X
p3.24.N <- sum(p3.24.f)
p3.24.fX.sum <- sum(p3.24.fX)
Table.3.6 <- matrix(c(p3.24.X, p3.24.f, p3.24.fX), nrow=p3.24.nrow)
colnames(Table.3.6) <- c('X', 'f', 'fX')

#### Table 3-6

In [ ]:
Table.3.6

\begin{align}
\bar{X}=\frac{\sum{fX}}{N}=\frac{\$19,845.00}{70}=\$283.50
\end{align}

In [ ]:
(p3.24.X.bar <- round(p3.24.fX.sum/p3.24.N, 2))