# Chapter 3 The Mean, Median, Mode, and Other Measures of Central Tendency

## Index, or subscript, notation

## Summation Notation

## Averages, or measures of central tendency

## Arithmetic mean

## The weighted arithmetic mean

## Properties of the arithmetic mean

## The arithmetic mean computed from grouped data

## The median

## The mode

## The empirical relation between the mean, median, and mode

## The Geometric mean G

## The harmonic mean H

## The relation between the arithmetic, geometric, and harmonic mean

## Quartiles, deciles, and percentiles

## Software and measures of central tendency

## Solved Problems

### Summation notation

In [3]:
# 3.5 The following table is the amount of taxes collected in the United States. Find what the sum is.
item <- c(
    "Sales and receipts",
    "Income",
    "Licenses",
    "Others",
    "Property"
)
amount.collected <- c(1051.42, 875.23, 144.33, 80.49, 38.36)
df <- data.frame(item,amount.collected)
df
sum(df$amount.collected)

  item               amount.collected
1 Sales and receipts 1051.42
2 Income              875.23
3 Licenses            144.33
4 Others               80.49
5 Property             38.36

[1] 2189.83

### The arithmetic mean

In [33]:
# 3.6 The grades of a student on six examinations are shown below what is the arithmetic mean.
X <- grades <- c(84, 91, 72, 68, 87, 78)
N <- length(X)
sum(X)/N
# OR
X.bar <- mean(X)
X.bar

[1] 80

[1] 80

In [30]:
# 3.7 Ten measurements of the diameter of a cylinder were recorded by a scientist. What is the arithmetic mean
X <- measurements <- c(3.88, 4.09, 3.92, 3.97, 4.02, 3.95, 4.03, 3.92, 3.98, 4.06)
X.bar <- round(mean(X),2)
X.bar

[1] 3.98

In [31]:
# 3.9 Arithmetic mean
X <- numbers <- c(5, 3, 6, 5, 4, 5, 2, 8, 6, 5, 4, 8, 3, 4, 5, 4, 8, 2, 5, 4)
X.bar <- mean(numbers)

In [35]:
# 3.10 Out of 100 numbers, 20 were 4's, 40 were 5's, 30 were 6's, and the remainder were 7's.
# Find the arithmetic mean
N <- 100
sevens <- N - 20 - 40 - 30
X <- set <- c(4, 5, 6, 7)
f <- c(20, 40, 30, sevens)
X.bar <- sum(f*X)/N
X.bar

[1] 5.3

In [38]:
# 3.11 A student's final grades in mathematics, physics, english and hygiene are, respectively, 82, 86, 90, and 70.
# If the respective credits received for these courses are 3, 5, 3, and 1, determine an appropriate average grade.

X <- grades <- c(82, 86, 90, 70)
N <- length(X)
w <- weights <- c(3, 5, 3, 1)
X.bar = sum(w*X)/sum(w)
round(X.bar,0)

[1] 85

In [42]:
# 3.12 In a company having 80 employees, 60 earn $10.00 per hour and 20 earn $13.00 per hour.
#
# (a) Determine the mean earnings per hour.
# (b) Would the answer in part (a) be the same if the 60 employees earn a mean hourly wage of
#     $10.00 per hour? Prove your answer.
# (c) Do you believe the mean hourly wage to be typical?

X <- earnings <- c(10.00, 13)
f <- weights <- c(60, 20)
N <- sum(f)
round(sum(X*f)/N,2)

[1] 10.75

In [28]:
# 3.13 Four groups of students, consisting of 15, 20, 10, and 18 individuals,
# reported mean weights of 162, 148, 153, and 140 pounds (lb), respectively. 
# Find the mean weight of all the students.
X <- student.weights <- c(162, 148, 153, 140)
f <- num.students <- c(15, 20, 10, 18)
N <- sum(f)
round(sum(f*X)/sum(N))

[1] 150

In [27]:
# 3.15 Use the following frequency distribution of heights to find the mean height of the 100 male
# students.

height.classes <- c(
    "60-62",
    "63-65",
    "66-68",
    "69-71",
    "72-74"
)
f <- number.of.students <- c(5, 18, 42, 27, 8)
N <- sum(f)
df <- data.frame(height.classes, number.of.students)
df
X <- class.marks <- c(61, 64, 67, 70, 73)
round(sum(f*X)/N,2)

  height.classes number.of.students
1 60-62           5
2 63-65          18
3 66-68          42
4 69-71          27
5 72-74           8

[1] 67.45

### Properties of the arithmetic mean

#### 3.16
Prove that the sum of the deviations of $X_1, X_2,...,X_N$ from their mean $\bar{X}$ is equal to zero.

#### Solution
Let $d_1 = X_1 - \bar{X}, d_2 = X_2 - \bar{X},...,d_N = X_N - \bar{X}$ be the deviations of
$X_1, X_2,...,X_N$ from their mean $\bar{X}$. Then

$$
\begin{align*}
\text{Sum of deviations}
= \sum{d_j}
= \sum{(X_j - \bar{X})}
= \sum{X_j} - N\bar{X}
= \sum{X_j} - N\left(\frac{\sum{X_j}}{N}\right)
= \sum{X_j} - \sum{X_j} = 0
\end{align*}
$$

where we have used $\sum$ in place of $\sum_{j=1}^N$. We could, if desired, have omitted the subscript $j$ in $X_j$, provided that it is _understood_.

#### 3.17
If $Z_1 = X_1 + Y_1, Z_2 = X_2 + Y_2,...,Z_N = X_N + Y_N$, prove that $\bar{Z} = \bar{X} + \bar{Y}$.

#### Solution
By definition,
$$
\begin{align*}
\bar{X} = \frac{\sum{X}}{N}
\ \ \ \ \ \ \ \ \ \ \ 
\bar{Y} = \frac{\sum{Y}}{N}
\ \ \ \ \ \ \ \ \ \ \ 
\bar{Z} = \frac{\sum{Z}}{N}
\end{align*}
$$
Thus
$$
\begin{align*}
\bar{Z}
= \frac{\sum{Z}}{N}
= \frac{\sum{(X+Y)}}{N}
= \frac{\sum{X}+\sum{Y}}{N}
= \frac{\sum{X}}{N}+\frac{\sum{Y}}{N}
= \bar{X} + \bar{Y}
\end{align*}
$$

where the subscripts $j$ on $X$, $Y$, and $Z$ have been omitted and where $\sum$ means $\sum_{j=1}^N$.

#### 3.18
(a) If $N$ numbers $X_1, X_2,...,X_N$ have deviations from any number $A$ given by $d_1 = X_1 - A$, 
$d_2 = X_2 - A,...,d_N = X_N - A$, respectively, prove that:

$$
\begin{align*}
\bar{X} = A + \frac{\sum_{j=1}^N{d_j}}{N} = A + \frac{\sum{d}}{N}
\end{align*}
$$


(b) In case $X_1, X_2,...,X_K$ have respective frequencies $f_1, f_2,...,f_K$ and 
$d_1 = X_1 - A,...,d_K = X_K - A$, show that the result in part (a) is replaced with

$$
\begin{align*}
\bar{X} = A + \frac{\sum_{j=1}^K{f_jd_j}}{\sum_{j=1}^K{f_j}} = A + \frac{\sum{fd}}{N}\text{   where   }
\sum_{j=1}^K{f_j} = \sum{f} = N
\end{align*}
$$

#### Solution (a) First method
$$
\begin{align*}
\bar{X} = A + \frac{\sum{X_j}}{N} = \frac{\sum(A+d_j)}{N} = \frac{\sum{A}+\sum{d_j}}{N} = \frac{NA+\sum{d_j}}{N}=
A+\frac{\sum{d_j}}{N}
\end{align*}
$$

where we have used $\sum$ in place of $\sum_{j=1}^N$ for brevity.

#### Solution (a) Second method
We have $d=X-A$, or $X=A+d$, omitting the subscripts on $d$ and $X$. Thus, by Problem 3.17,

$$
\begin{align*}
\bar{X} = \bar{A}+\bar{d} = A + \frac{\sum{d}}{N}
\end{align*}
$$

since the mean of a number of constants all equal to $A$ is $A$.

#### Solution (b)
$$
\begin{align*}
\bar{X}
= \frac{\sum_{j=1}^K{f_jX_j}}{\sum_{j=1}^K{f_j}}
= \frac{\sum{f_jX_j}}{N}
= \frac{\sum{f_j(A+d_j)}}{N}
= \frac{\sum{Af_j} + \sum{f_jd_j}}{N}
= \frac{A\sum{f_j} + \sum{f_jd_j}}{N}
= \frac{AN + \sum{f_jd_j}}{N}
= A + \frac{\sum{f_jd_j}}{N}
= A + \frac{\sum{fd}}{N}
\end{align*}
$$

Note that _formally_ the result is obtained from part (a) by replacing $d_j$ with $f_jd_j$ and summing from
$j = 1$ to $K$ instead of from $j = 1$ to $N$. The result is equialent to $\bar{X} = A + \bar{d}$, where
$\bar{d} = \left(\sum{fd}\right)/N$

### The arithmetic mean computed from grouped data

In [25]:
# 3.19 Use the method of Problem 3.18(a) to find the arithmetic mean of the numbers 
# 5, 8, 11, 9, 12, 6, 14, and 10, choosing as the "guessed mean" A the values (a) 9 and (b) 20.
set <- c(5, 8, 11, 9, 12, 6, 14, 10)
N <- length(set)
guess.a <- 9
guess.b <- 20
sum.d.a <- sum(set - guess.a)
sum.d.b <- sum(set - guess.b)
guess.a + (sum.d.a/N)
guess.b + (sum.d.b/N)

[1] 9.375

[1] 9.375

In [26]:
# 3.20 Use the method of Problem 3.18(b) to find the arithmetic mean of the heights of the 100 male students
# at XYZ University.
height.classes <- c(
    "60-62",
    "63-65",
    "66-68",
    "69-71",
    "72-74"
)
f <- number.of.students <- c(5, 18, 42, 27, 8)
N <- sum(f)
df <- data.frame(height.classes, number.of.students)
df
X <- avg.class.height <- c(61, 64, 67, 70, 73)
A <- guess <- 67
d <- X - A
x.bar <- avg <- A + sum(f*d)/N
x.bar

  height.classes number.of.students
1 60-62           5
2 63-65          18
3 66-68          42
4 69-71          27
5 72-74           8

[1] 67.45