# The class mark
The _class mark_ is the midpoint of the class interval and is obtained by adding the lower and upper class limits and by dividing by $2$. Thus the class mark of the interval `60-62` is $(60+62)/2=61$. The class mark is also called the _class midpoint_.

For purposes of further mathematical analysis, all observations belonging to a given class interval are assumed to coincide with the class mark. Thus all heights in the class interval `60-62` in are considered to be $61$ in.

---

In [1]:
load('../../Saves/Table_2.1.Rdata')
Table.2.1

  Height Freq
1 60-62   5
2 63-65  18
3 66-68  42
4 69-71  27
5 72-74   8

Using the class limits and the class interval $c$, we can generate the class marks $X$:

In [2]:
c <- 3
lower.limits <- seq(60, 72, by=c)
upper.limits <- seq(62, 74, by=c)
X <- (upper.limits+lower.limits)/2
data.frame(Table.2.1$Height, X, Table.2.1$Freq)

  Table.2.1.Height X  Table.2.1.Freq
1 60-62            61  5
2 63-65            64 18
3 66-68            67 42
4 69-71            70 27
5 72-74            73  8