# The class mark
The _class mark_ is the midpoint of the class interval and is obtained by adding the lower and upper class limits and by dividing by $2$. Thus the class mark of the interval `60-62` is $(60+62)/2=61$. The class mark is also called the _class midpoint_.

For purposes of further mathematical analysis, all observations belonging to a given class interval are assumed to coincide with the class mark. Thus all heights in the class interval `60-62` in are considered to be $61$ in.

---

In [2]:
load('../../Saves//Table_2.1.Rdata')
Table.2.1

      [,1]
60-62  5
63-65 18
66-68 42
69-71 27
72-74  8

In [5]:
X <- c(61, 64, 67, 70, 73)
Table.2.1.marks <- matrix(c(X, Table.2.1[,1]), nrow=nrow(Table.2.1))
colnames(Table.2.1.marks) <- c('X', 'f')
rownames(Table.2.1.marks) <- rownames(Table.2.1)
Table.2.1.marks

      X  f
60-62 61  5
63-65 64 18
66-68 67 42
69-71 70 27
72-74 73  8