# The mean deviation

## Problem 4-3
Find the mean deviation of the sets of numbers in Problem [4.1](#Problem-4-1).

In [1]:
p4.3 <- new.env()
p4.3$Data.a <- c(12, 6, 7, 3, 15, 10, 18, 5)
p4.3$Data.b <- c(9, 3, 8, 8, 9, 8, 9, 18)

### Solution 4-3
(a) The arithemtic mean is

\begin{align}
\bar{X} = \frac{12 + 6 + 7 + 3 + 15 + 10 + 18 + 5}{8} = \frac{76}{8} = 9.5
\end{align}

The mean deviation is

\begin{align}
\text{MD} &= \frac{\sum{\left\lvert X - \bar{X} \right\rvert}}{N} \\
          &= \frac{\left\lvert12 - 9.5\right\rvert + \left\lvert6 - 9.5\right\rvert + \left\lvert7 - 9.5\right\rvert + \left\lvert3 - 9.5\right\rvert +
             \left\lvert15 - 9.5\right\rvert + \left\lvert18 - 9.5\right\rvert + \left\lvert5 - 9.5\right\rvert}{8} \\
          &= \frac{2.5 + 3.5 + 2.5 + 6.5 + 5.5 + 0.5 + 8.5 + 4.5}{8} = \frac{34}{8} = 4.25
\end{align}

(b)

\begin{align}
\bar{X} = \frac{9 + 3 + 8 + 8 + 9 + 8 + 9 + 18}{8} = \frac{72}{8} = 9
\end{align}

\begin{align}
\text{MD} &= \frac{\sum{\left\lvert X - \bar{X}\right\rvert}}{N} \\
          &= \frac{\left\lvert9 - 9\right\rvert + \left\lvert3 - 9\right\rvert + \left\lvert8 - 9\right\rvert + \left\lvert8 - 9\right\rvert +
             \left\lvert9 - 9\right\rvert + \left\lvert8 - 9\right\rvert + \left\lvert9 - 9\right\rvert + \left\lvert18 - 9\right\rvert}{8} \\
          &= \frac{0 + 6 + 1 + 1 + 0 + 1 + 0 + 9}{8} = 2.25
\end{align}

The mean deviation indicates taht set (b) shows less dispersion than set (a), as it should.

In [13]:
cat('(a) The arithmetic mean is: ', (p4.3$Mean.a <- mean(p4.3$Data.a)), '\n')
p4.3$MD.a <- sum(abs(p4.3$Data.a - p4.3$Mean.a))/length(p4.3$Data.a)
cat('    The mean deviation is: ', p4.3$MD.a, '\n\n')
cat('(b) The arithmetic mean is: ', (p4.3$Mean.b <- mean(p4.3$Data.b)), '\n')
p4.3$MD.b <- sum(abs(p4.3$Data.b - p4.3$Mean.b))/length(p4.3$Data.b)
cat('    The mean deviation is: ', p4.3$MD.b, '\n')

(a) The arithmetic mean is:  9.5
    The mean deviation is:  4.25

(b) The arithmetic mean is:  9
    The mean deviation is:  2.25

In [14]:
rm(p4.3)

---

## Problem 4-4
Find the mean deviation of the heights of the $100$ male students at XYZ University (see Table [3.2](#Table-3-2)

In [22]:
load('../../Saves/Table_3.2.Rdata')
Table.3.2

  Height X  Deviation Freq fd
1 60-62  61 -6         5   -30
2 63-65  64 -3        18   -54
3 66-68  67  0        42     0
4 69-71  70  3        27    81
5 72-74  73  6         8    48

### Solution 4-4
From Problem [3.20](#Problem-3-20), $\bar{X}=67.45$ in. The work can be arranged as in Table [4.1](#Table-4-1). It is also possible to devise a coding method for computing the mean deviation (see Problem [4.47](#Problem-4-47)).

In [42]:
p4.4 <- new.env()
p4.4$X.bar <- 67.45
p4.4$X.X.bar <- round(abs(Table.3.2$X - p4.4$X.bar),2)
p4.4$Freq <- Table.3.2$Freq
p4.4$f.X.X.bar <- p4.4$Freq*p4.4$X.X.bar
Table.4.1 <- data.frame(Height=Table.3.2$Height, X=Table.3.2$X, X.X.bar=p4.4$X.X.bar, Freq=p4.4$Freq, f.X.X.bar=p4.4$f.X.X.bar)

#### Table 4-1

In [45]:
Table.4.1

  Height X  X.X.bar Freq f.X.X.bar
1 60-62  61 6.45     5   32.25
2 63-65  64 3.45    18   62.10
3 66-68  67 0.45    42   18.90
4 69-71  70 2.55    27   68.85
5 72-74  73 5.55     8   44.40

\begin{align}
\text{MD} = \frac{\sum{f\left\lvert X - \bar{X}\right\rvert}}{N} = \frac{226.50}{100} = 2.26\text{ in}
\end{align}

In [38]:
cat('Mean Deviation: ', (p4.4$MD <- sum(Table.4.1$f.X.X.bar)/sum(Table.4.1$Freq)))

Mean Deviation:  2.265

In [39]:
rm(p4.4)

---

## Problem 4-5
Determine the percentage of the student's heights in Problem [4.4](#Problem-4-4) that fall within the ranges (a) $\bar{X}\pm\text{MD}$, (b) $\bar{X}\pm2\text{MD}$, and (c) $\bar{X}\pm3\text{MD}$.

### Solution 4-5
(a) The range from $65.19$ to $69.71$ in is $\bar{X}\pm\text{MD} = 67.45\pm2.26$. This range includes all individuals in the third class $+\frac{1}{3}(65.5 - 65.19)$ of the students in the second class $+\frac{1}{3}(69.71 - 68.5)$ of the students in the fourth class (since the class-interval size is $3$ in, the upper class boundary of the second class is $65.5$ in, and the lower class boundary of the fourth class is $68.5$ in). The number of students in the range $\bar{X}\pm\text{MD}$ is

\begin{align}
42 + \frac{0.31}{3}(18) + \frac{1.21}{3}(27) = 42 + 1.86 + 10.89 = 54.75 \qquad \text{or} \quad 55
\end{align}

which is $55\%$ of the total.

(b) The range from $62.93$ to $71.97$ in is $\bar{X}\pm2\text{MD} = 67.45\pm2(2.26)=67.45\pm4.52$. The number of students inthe range $\bar{X}\pm2\text{MD}$ is

\begin{align}
18 + \left(\frac{62.93 - 62.5}{3}\right)(18) + 42 + 27 + \left(\frac{71.97 - 71.5}{3}\right)(8) = 85.67 \qquad \text{or} \quad 86
\end{align}

which is $86%$ of the total.

(c) The range from $60.67$ to $74.23$ in is $\bar{X}\pm3\text{MD} = 67.45\pm3(2.26) = 67.45\pm6.78$. The number of students in the range $\bar{X}\pm3\text{MD}$ is

\begin{align}
5 - \left(\frac{60.67 - 59.5}{3}\right)(5) + 18 + 42 + 27 + \left(\frac{74.5 - 74.23}{3}\right)(8) = 97.33 \qquad \text{or} \quad 97
\end{align}

which is $97\%$ of the total.

In [84]:
p4.5 <- new.env()
load('../../Saves/Table_4.1.Rdata')
(p4.5$Freq <- Table.4.1$Freq)
p4.5$C <- 3
p4.5$Class.Boundaries <- seq(59.5, 74.5, by=3)
p4.5$X.bar <- 67.45
p4.5$MD.R <- c(-2.26, 2.26)
p4.5$X.MD <- p4.5$X.bar + p4.5$MD.R
p4.5$Pct.X.MD <- round(p4.5$Freq[3] +
                  p4.5$Freq[2]*(p4.5$Class.Boundaries[3]-p4.5$X.MD[1])/p4.5$C +
                  p4.5$Freq[4]*(p4.5$X.MD[2]-p4.5$Class.Boundaries[4])/p4.5$C,2)

p4.5$X.2MD <- p4.5$X.bar + 2*p4.5$MD.R
p4.5$Pct.X.2MD <- round( p4.5$Freq[3] + p4.5$Freq[4] +
                          p4.5$Freq[2] - p4.5$Freq[2]*(p4.5$X.2MD[1] - p4.5$Class.Boundaries[2])/p4.5$C +
                          p4.5$Freq[5]*(p4.5$X.2MD[2] - p4.5$Class.Boundaries[5])/p4.5$C,2)

p4.5$X.3MD <- p4.5$X.bar + 3*p4.5$MD.R
p4.5$Pct.X.3MD <- round( p4.5$Freq[3] + p4.5$Freq[4] + p4.5$Freq[2] +
                          p4.5$Freq[1] - p4.5$Freq[1]*(p4.5$X.3MD[1] - p4.5$Class.Boundaries[1])/p4.5$C +
                          p4.5$Freq[5]*(p4.5$Class.Boundaries[6] - p4.5$X.3MD[2])/p4.5$C,2)

[1]  5 18 42 27  8

In [85]:
cat("First mean deviation: ", p4.5$Pct.X.MD, "%\n", sep="")
cat("Second mean deviation: ", p4.5$Pct.X.2MD, "%\n", sep="")
cat("Third mean deviation: ", p4.5$Pct.X.3MD, "%\n", sep="")

First mean deviation: 54.75%
Second mean deviation: 85.67%
Third mean deviation: 90.77%

In [86]:
rm(p4.5)

---